Move binary in /usr/bin
arduino/arduino-connector pull request #283
Opened 2020-08-28 13:51 UTC by guerinoni

This fix #234, in this way the path for service is /usr/bin and during
script of installation will be moved in that path.

Signed-off-by: Federico Guerinoni <guerra@develer.com>

2020-09-01 11:45 UTC, rsora approved these changes

2020-09-17 07:01 UTC, rsora approved these changes

2020-09-17 10:32 UTC, Pippolo84 requested changes
The `WorkingDirectory` is wrong. We need to address that issue before merging.

2020-09-17 10:32 UTC, Pippolo84 commented on install.go
> +		WorkingDirectory: "/usr/bin",
The `WorkingDirectory` must be the path where the certificates and `arduino-connector.cfg` are. Probably we should create a dedicated folder where to move those files (in the installation script) and save that path here.

2020-09-17 12:19 UTC, Pippolo84 approved these changes

2020-09-17 15:21 UTC, merged