Feature/tests apt
arduino/arduino-connector pull request #284
Opened 2020-09-01 10:28 UTC by guerinoni

Add the first part of tests for apt APIT

2020-09-01 11:48 UTC, rsora requested changes

2020-09-01 11:48 UTC, rsora commented on .github/workflows/tests.yml
> +    container: guerra1994/go-mosquitto-ubuntu-env
Can you please add the Dockerfile for this Image?

2020-09-01 14:37 UTC, rsora approved these changes

2020-09-01 15:16 UTC, guerinoni commented on .github/workflows/tests.yml
> +    container: guerra1994/go-mosquitto-ubuntu-env
@rsora 
I added this Dockerfile but there is also another image and is not a simple docker file. For now, docker images are hosted on my GH https://github.com/guerinoni/go-mqtt-docker-env and https://github.com/guerinoni/go-mosquitto-ubuntu-env, if you want we can move this repo in `arduino` GH or add it as submodules
As you prefer...

2020-09-01 16:19 UTC, Pippolo84 requested changes
Please fix that minor style issue

2020-09-01 16:19 UTC, Pippolo84 commented on handlers_apt_repositories_test.go
> +	}
```suggestion
	assert.NotEmpty(t, resp)
```

2020-09-02 07:18 UTC, rsora commented on .github/workflows/tests.yml
> +    container: guerra1994/go-mosquitto-ubuntu-env
Please add them under the Arduino org, documenting, and providing links in the readme in a proper section. :+1:

2020-09-25 09:14 UTC, Pippolo84 approved these changes

2020-09-25 09:14 UTC, merged