Uninstall
arduino/arduino-connector pull request #288
Opened 2020-09-17 07:21 UTC by guerinoni

This PR solve #80, in order to uninstall only packages installed through arduino-connector during installation will create a config file listing packages already present, like network-manager, docker (images + container), and so on... 
The uninstall feature is called by API `/status/uninstall/post` and at the end of the uninstall process it creates a script (uninstall-arduino-connector.sh) for the user that must run to finalize the uninstall process. This because is impossible to stop and remove service from within arduino-connector, that script removes also the binary.

2020-10-05 08:23 UTC, Pippolo84 requested changes
Please review and (eventually) apply the suggested changes.

2020-10-05 08:23 UTC, pippolo84 commented on uninstall.go
> +	s.SendInfo(s.topicPertinence+"/status/uninstall", string(data))
```suggestion
	if err := removeSketches(s); err != nil {
		panic(err)
	}

	if err := removeCerts(s); err != nil {
		panic(err)
	}

	if err := removeContainers(s); err != nil {
		panic(err)
	}

	if err := removeImages(s); err != nil {
		panic(err)
	}

	if err := removeNetworkManager(); err != nil {
		panic(err)
	}

	if err := generateScriptUninstall(); err != nil {
		panic(err)
	}

	s.SendInfo(s.topicPertinence+"/status/uninstall", "OK")
```

2020-10-05 08:23 UTC, pippolo84 commented on uninstall.go
> +	}
```suggestion
	if err := os.Remove(pem); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
```

2020-10-05 08:23 UTC, pippolo84 commented on uninstall.go
> +	}
```suggestion
	if err := os.RemoveAll(folder); err != nil {
		return err
	}
```
`os.RemoveAll` won't return any errors if `folder` does not exist: https://golang.org/pkg/os/#RemoveAll

2020-10-05 08:23 UTC, pippolo84 commented on uninstall.go
> +	}
```suggestion
	if err := os.Remove(key); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
```

2020-10-05 08:23 UTC, pippolo84 commented on uninstall.go
> +	viper.SetConfigFile(dir + string(os.PathSeparator) + "arduino-connector.yml")
```suggestion
	viper.SetConfigFile(filepath.Join(dir,  "arduino-connector.yml"))
```

2020-10-05 08:23 UTC, pippolo84 commented on uninstall.go
> +		err = s.dockerClient.ContainerRemove(context.Background(), v, types.ContainerRemoveOptions{Force: true})
We should probably use a `context.WithTimeout` here, to avoid blocking indefinitely on `ContainerRemove`

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall.go
> +		time.Sleep(5 * time.Second)
Is this needed to avoid some kind of strange errors with the Docker client?

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall.go
> +	viper.SetConfigFile(dir + string(os.PathSeparator) + "arduino-connector.yml")
```suggestion
	viper.SetConfigFile(filepath.Join(dir, "arduino-connector.yml"))
```

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall.go
> +	viper.SetConfigFile(dir + string(os.PathSeparator) + "arduino-connector.yml")
```suggestion
	viper.SetConfigFile(filepath.Join(dir, "arduino-connector.yml"))
```

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall.go
> +	if !beforeNotInstalled && nowInstalled {
I suggest to change `beforeNotInstalled` with `before` and `nowInstalled` with `now`

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall.go
> +	fmt.Println(dir)
```suggestion
```

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall.go
> +	file, errFile := os.Create(dir + "/uninstall-arduino-connector.sh")
```suggestion
	file, errFile := os.Create(filepath.Join(dir, "uninstall-arduino-connector.sh"))
```

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall.go
> +	return err
```suggestion
	data := `sudo systemctl stop ArduinoConnector.service
sudo systemctl disable ArduinoConnector.service
sudo rm /etc/systemd/system/ArduinoConnector.service
sudo systemctl daemon-reload
sudo systemctl reset-failed
sudo rm -f arduino-connector`

	_, err := file.WriteString(data)

	return err
```

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall_test.go
> +		err := os.Remove(dir + "/uninstall-arduino-connector.sh")
```suggestion
		err := os.Remove(filepath.Join(dir, "uninstall-arduino-connector.sh"))
```

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall_test.go
> +	_, err := os.Stat(dir + "/uninstall-arduino-connector.sh")
```suggestion
	_, err := os.Stat(filepath.Join(dir, "uninstall-arduino-connector.sh"))
```

2020-10-05 08:23 UTC, Pippolo84 commented on uninstall_test.go
> +		}
```suggestion
		switch v.ID {
		case containerMustKeep.ID:
			found = true
		case containerMustRemove.ID:
			assert.Fail(t, "Container ID %s found, but should have been removed", containerMustRemove.ID)
		}
```

2021-04-09 15:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/arduino-connector?pullRequest=288) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino/arduino-connector?pullRequest=288) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/arduino-connector?pullRequest=288) it.</sub>

2021-10-22 17:51 UTC, guerinoni commented
@rsora maybe we can merge it? :)

2023-04-24 07:28 UTC, closed without merging